#!/bin/bash
# This set fixes up the profile.  Run for each user!

# Find repo root.
SCRIPTPATH=$( cd $(dirname $0) ; pwd -P )
repo=${SCRIPTPATH%/scripts*}

# Startup items to remove from gnome-session (gnome-session-properties):
startup_items=( at-spi-dbus-bus.desktop
caribou-autostart.desktop
gnome-sound-applet.desktop
imsettings-start.desktop
libcanberra-login-sound.desktop
nautilus-autostart.desktop
spice-vdagent.desktop
user-dirs-update-gtk.desktop
)

a_s_dir=~/.config/autostart
# Create a local autostart dir
[ -d $a_s_dir ] || mkdir -p $a_s_dir
# Edit items to override from system autostart while copying
for item in ${startup_items[@]}; do
    [ -f /etc/xdg/autostart/$item ] && \
         sed -e '
             /X-GNOME-Autostart-enabled/ {
                s/true/false/I
                # Tuck into hold buffer
                h
            }
            $ {
                x
                # If the hold buffer was empty, then we didnt match
                /^$/ a\
                X-GNOME-Autostart-enabled=false
            }
        ' < /etc/xdg/autostart/$item > $a_s_dir/$item
done

# clone gorilla password safe
gor_dir=~/bin/gorilla
[ -d ~/bin/gorilla ] || mkdir -p ~/bin/gorilla
(
    cd ~/bin/
    [ -d gorilla/.git ] || git clone git://github.com/zdia/gorilla.git
    cd gorilla && git checkout v1.5.3.6.3
)
ln -f -s ~/bin/gorilla/sources/gorilla.tcl ~/bin/gorilla-1.5.3.6.3
mkdir -p ~/.local/share/applications
cp -f $repo/home/local/share/applications/gorilla-1.5.3.6.3.desktop ~/.local/share/applications

# Set up gnome-shell auto-move-windows:
gsettings set org.gnome.shell.extensions.auto-move-windows application-list \
    "['gnome-terminal.desktop:1','firefox.desktop:2','mozilla-thunderbird.desktop:3']"

# Remove a couple icons
gsettings set org.gnome.shell.extensions.icon-manager top-bar \
    "['a11y']"

# Enable extensions: maximus axe-menu auto-move-windows icon-manager,
#    pidgin-integration, alternate-tab
ext_uuids="maximus@mathematical.coffee.gmail.com
axemenu@wheezy
alternate-tab@gnome-shell-extensions.gcampax.github.com
auto-move-windows@gnome-shell-extensions.gcampax.github.com
icon-manager@krajniak.info
pidgin-conversation-integration@kagesenshi.org"
for ext in $ext_uuids; do
    # This tool complains loudly if the extensions are already enabled.
    gnome-shell-extension-tool -e "$ext" 2>/dev/null
done

# Set up syndaemon autostart
cp $repo/home/config/autostart/syndaemon.desktop ~/.config/autostart
# Disable gnome control of synaptics vars
gsettings set org.gnome.settings-daemon.plugins.mouse active false

# Install dotfiles (copy for screen and...)
cd $repo/home

for f in $(find . -type f); do
    # If it's a file, back that shit up.
    # If it's a link already, leave it alone.
    f=${f#./}
    [ -h ~/.$f ] || ln -b -s $repo/home/$f ~/.$f
done

# Fix ssh perms
chmod -R go-rwx $repo/home/ssh
# Install and update vim settings.

cd ~/.vim
if [ ! -d ~/.vim/.git ]; then
    git clone git@github.com:dwlocks/dotvim.git ~/.vim
    git submodule update --init
    ln -s .vim/vimrc .vimrc
    ln -s .vim/gvimrc .gvimrc
else
    git pull origin
fi
cd ..
