#!/bin/sh

# Disable ethernet on wake if no link
echo "$(cat /sys/class/net/eth0/carrier)"
case $1 in
    thaw|resume)
        [ $(cat /sys/class/net/eth0/carrier) -eq 0 ] && ifconfig eth0 down
        ;;
esac
